### ISSUE TITLE
Tab navigator not working properly

### ISSUE THREAD

**Issue by SandipNirmal** [SandipNirmal/LaLuneiOSClone#5]
Getting blank screen when navigating using tabNavigator.

**Comment by uktg** [comment]
@SandipNirmal Do you still see this issue?

**Comment by SandipNirmal** [comment]
Yes.

**Comment by uktg** [comment]
Looks like something changed in react-navigation. This seems to be working on version 1.0.3, fails on version 1.1.2. Updating package.json to use version 1.0.3 for now

**Comment by SandipNirmal** [comment]
It was a bug caused by the newer version of react-navigation. Issue fixed with commit https://github.com/SandipNirmal/LaLuneiOSClone/commit/33932586b0990f4c742a640e6d61672885855c14.
