### ISSUE TITLE
Fix the issue in Search>Person

### ISSUE THREAD

**Issue by uktg** [SandipNirmal/LaLuneiOSClone#9]
### How to reproduce?

1. Tap Search
2. Tap Person
3. Search for a person
4. Click on a result
5. In the details page, click any Known For item

### Expected behavior
Should take to either the TvShow details or Movie Details

### Observed
Crash

**Comment by SandipNirmal** [comment]
Fixed with https://github.com/SandipNirmal/React-Native-MovieDB/commit/eed00c461a0c83eec3b2cae7043a842a7892573f.
